name: CI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Use the latest Node.js for building
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/ # Adjust to your build output directory

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12, 14, 16, 18, 20, 22]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      - name: Create minimal test environment (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          if exist node_modules rmdir /s /q node_modules
          npm install --production
          npm install tape tap-spec
      - name: Create minimal test environment (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          rm -rf node_modules
          npm install --production
          npm install tape tap-spec
      - name: Run tests
        run: node test/test.js
